name: Go - Publish pkg.dev

on: 
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Notify pkg.dev of new version
        run: curl "https://proxy.golang.org/github.com/stscoundrel/PROJECT-NAME/@v/${{ github.ref_name }}.info"
